spring:
  application:
    name:RESTApiWithJPA

  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
